config/routes.rb
IWonder::Engine.routes.draw do
  get "dashboard" => "dashboard#landing"

  resources :ab_tests
  resources :reports
  resources :metrics
  resources :events, :only => [:index, :show]
  
  root :to => "dashboard#landing"
end

app/models/i_wonder/ab_test.rb
module IWonder
  class AbTest < ActiveRecord::Base
    attr_accessible :name, :sym, :description, :ab_test_goals_attributes, :test_applies_to, :test_group_names, :options, :test_group_data
    attr_writer :skip_file_save
    serialize :options, Hash
    serialize :test_group_data, Hash
    
    has_many :test_group_memberships, :dependent => :destroy, :foreign_key => "ab_test_sym", :primary_key => :sym

    has_many :ab_test_goals, :dependent => :destroy, :foreign_key => "ab_test_sym", :primary_key => "sym"
    accepts_nested_attributes_for :ab_test_goals, :allow_destroy => true
    
    hash_accessor :options, :test_group_names, :type => :array, :reject_blanks => true
    
    validates_presence_of :name, :on => :create, :message => "can't be blank"
    validates_uniqueness_of :name, :on => :create, :message => "must be unique"
    validates_presence_of :sym, :on => :create, :message => "can't be blank"
    validates_format_of :sym, :with => /^[\w\d\_]+$/, :on => :create, :message => "can only contain letters, numbers and underscores"
    validates_uniqueness_of :sym, :on => :create, :message => "must be unique"
    validates_inclusion_of :test_applies_to, :in => %w( session user account ), :on => :create, :message => "extension %s is not included in the list"
    
    
    # ----------------------------------------------------------------------------------------------------------------------------------------
    # These two methods should NOT be needed. For some reason the accepts_nested_attributes_for is not autosaving or deleting associated goals
    
    def ab_test_goals_attributes=(hash)
      hash.each{|key,value|
        goal = self.ab_test_goals.detect{|tg| tg.id == value["id"].to_i}
        goal ||= self.ab_test_goals.build
        goal.attributes = value
        
        if value["_destroy"] =~ /true|1/ or value["_destroy"].is_a?(TrueClass)
          goal.mark_for_destruction
        end
      }
    end
    before_save :remove_deleted_test_goals
    def remove_deleted_test_goals
      ab_test_goals.select(&:marked_for_destruction?).each(&:destroy)
      ab_test_goals.each(&:save)
    end
    
    
    # ----------------------------------------------------------------------------------------------------------------------------------------
      
    
    validate :has_two_groups_and_a_goal
    def has_two_groups_and_a_goal
      unless test_group_names.length >= 2
        errors.add(:base, "Must have atleast two test groups")
      end
      
      if ab_test_goals.reject(&:marked_for_destruction?).length == 0
        errors.add(:base, "Must have atleast one goal")
      end
    end
      
    after_save :save_to_file
    def save_to_file
      unless @skip_file_save
        AbTesting::Loader.save_ab_test(self)
      end
    end
      
    after_destroy :remove_file
    def remove_file
      AbTesting::Loader.remove_file_for(self)
    end
      
    def started?
      test_group_memberships.count > 0
    end
    
    def which_test_group?(current_controller)
      if(current_group = get_current_group(current_controller))
        return current_group.test_group_name
      else
        begin
          test_group = add_to_test_group(randomly_chosen_test_group, current_controller)
        rescue Exception => e
          # If there is some error, just return a randome option. Better not to crash
          # TODO: this should warn developer somehow
          return randomly_chosen_test_group
        end
        return test_group.test_group_name
      end
    end
    
    def assigned_count(test_group_name)
      self.test_group_memberships.where(:test_group_name => test_group_name).count
    end
    
    def get_results_for(test_group_name, ab_test_goal)
      scoped_test_group_memberships  = self.test_group_memberships.where(:test_group_name => test_group_name).scoped

      if test_applies_to =~ /account/i
        event_membership_key = "account_id"
      elsif test_applies_to =~ /user/i
        event_membership_key = "user_id"
      else
        event_membership_key = "session_id"
      end
      
      scoped_groups_with_events = scoped_test_group_memberships.joins("LEFT JOIN i_wonder_events ON i_wonder_events.#{event_membership_key} = i_wonder_test_group_memberships.member_id")
      
      scoped_groups_with_goal_events = ab_test_goal.add_goal_to_query(scoped_groups_with_events)
      
      scoped_groups_with_goal_events = scoped_groups_with_goal_events.select("COUNT(DISTINCT i_wonder_events.#{event_membership_key}) as count_all")
      
      AbTest.connection.execute(scoped_groups_with_goal_events.to_sql)[0]["count_all"].to_i
    end

    def from_xml(xml)
      [super]
      
      # make sure it's not blank. Then make sure it's a hash. Then Make sure it's symbolized.
      self.options ||= {}
      self.test_group_data ||= {}
      self.options = {} if self.options.is_a?(String)
      self.test_group_data = {} if self.test_group_data.is_a?(String)
      self.options.symbolize_keys!
      self.test_group_data.symbolize_keys!
      
      self.ab_test_goals.each(&:mark_for_destruction)
      
      hash = Hash.from_xml(xml)
      hash["ab_test"]["ab_test_goals"].each{|ab_test_goal_hash|
        ab_test_goal_hash["options"].symbolize_keys!
        self.ab_test_goals.build(ab_test_goal_hash)
      }
    end
    
    def started_at
      test_group_memberships.minimum(:created_at)
    end
    
  private
    
    def get_current_group(current_controller)
      if test_applies_to =~ /account/i
        env = current_controller.request.env
        test_group_memberships.where(:member_type => "account", :member_id => env[ENV_KEY]["account_id"].to_s).first
      elsif test_applies_to =~ /user/i
        env = current_controller.request.env
        test_group_memberships.where(:member_type => "user", :member_id => env[ENV_KEY]["user_id"].to_s).first
      else
        session_id = current_controller.send("cookies")[COOKIE_KEY+Logging::SESSION_KEY_NAME]
        test_group_memberships.where(:member_type => "session", :member_id => session_id.to_s).first
      end
    end
    
    def add_to_test_group(test_group_name, current_controller)
      if test_applies_to =~ /account/i
        env = current_controller.request.env
        test_group_memberships.create!(:member_type => "account", :member_id => env[ENV_KEY]["account_id"].to_s, :test_group_name => test_group_name)
      elsif test_applies_to =~ /user/i
        env = current_controller.request.env
        test_group_memberships.create!(:member_type => "user", :member_id => env[ENV_KEY]["user_id"].to_s, :test_group_name => test_group_name)
      else
        session_id = current_controller.send("cookies")[COOKIE_KEY+Logging::SESSION_KEY_NAME]
        test_group_memberships.create!(:member_type => "session", :member_id => session_id.to_s, :test_group_name => test_group_name)
      end
    end
    
    def randomly_chosen_test_group
      test_group_names[rand(test_group_names.length)]
    end
    
  end
end

app/models/i_wonder/ab_test_goal.rb
module IWonder
  class AbTestGoal < ActiveRecord::Base
    attr_accessible :goal_type, :event_type, :page_view_controller, :page_view_action, :options
    
    belongs_to :ab_test, :foreign_key => "ab_test_sym", :primary_key => :sym
    
    serialize :options, Hash
    hash_accessor :options, :goal_type, :default => "Event"
    hash_accessor :options, :event_type
    hash_accessor :options, :page_view_controller
    hash_accessor :options, :page_view_action
    
    validates_inclusion_of :goal_type, :in => ["Event", "Page View"]
    validates_presence_of :event_type, :if => :tracks_event?
    validates_presence_of :page_view_controller, :if => :tracks_page_view?
    
    before_validation :clean_up_controller
    def clean_up_controller
      if tracks_page_view?
        page_view_controller.gsub!("Controller", "")
        page_view_controller.downcase!
      end
    end
    
    def tracks_event?
      goal_type == "Event"
    end
    
    def tracks_page_view?
      goal_type == "Page View"
    end
    
    def add_goal_to_query(scoped_statement)
      if tracks_event?
        sc = scoped_statement.where("i_wonder_events.event_type = ?", event_type)
      else
        sc = scoped_statement.where("i_wonder_events.event_type = ? AND i_wonder_events.controller = ?", "hit", page_view_controller)
        
        if page_view_action.present?
          sc = sc.where("i_wonder_events.action = ?", page_view_action)
        end
      end
      
      sc.where("i_wonder_events.created_at > ?", self.ab_test.started_at) # event had to come after goal
    end
    
    def to_s
      if tracks_event?
        "#{event_type} occurred"
      elsif page_view_action.present?
        "#{page_view_controller}##{page_view_action} hit"
      else
        "any #{page_view_controller} hit"
      end
    end
    
  end
end

app/models/i_wonder/event.rb
module IWonder
  class Event < ActiveRecord::Base
    attr_accessible :event_type, :account_id, :user_id, :session_id, :controller, :action, :referrer, :user_agent, :remote_ip
    serialize :extra_details, Hash
   
    validates_presence_of :event_type, :on => :create, :message => "can't be blank"
    
    class << self
      def merge_session_to_user(session_id, user_id)
        # grab the session_id off of the new_visitor attached to that user
        new_visitor_event = Event.where(:user_id => user_id, :event_type => "new_visitor").first
        original_session_id = (new_visitor_event ? new_visitor_event.session_id : session_id)
        

        # for all events on the current session, attach the user and session from that first event
        update_all({:user_id => user_id, :session_id => original_session_id}, ["session_id = ? AND user_id IS NULL", session_id])
        
        # Change the new_visitor to a return_visit
        if new_visitor_event and original_session_id != session_id
          update_all({:event_type => "return_visit"}, ["user_id = ? AND event_type = ? AND id <> ?", user_id, "new_visitor", new_visitor_event.id])
        end
        
        
        # TODO: merge any tests on the session id over to the original session_id
        # remove any duplicates (going with the original)
        
        return original_session_id
      end
      # handle_asynchronously :merge_session_to_user
      
      
      def fast_create(attr_hash)
        attr_hash[:created_at] = Time.zone.now.utc
        attr_hash[:updated_at] = Time.zone.now.utc
        
        keys = [:event_type, :account_id, :user_id, :session_id, :controller, :action, :extra_details, :remote_ip, :user_agent, :referrer, :created_at, :updated_at]
        key_str = keys.collect(&:to_s).join(", ")
        
        pre_value = keys.collect{ "?" }.join(", ")
        values_array = keys.collect{|k|
          v = attr_hash[k] 
          if v.is_a?(Hash)
            v = v.delete_blank.to_yaml
          elsif v.is_a?(String)
            v = v.truncate(200)
          end
          v
        }
        value_str = sanitize_sql_array( [pre_value] +  values_array) 
        
        Event.connection.execute "INSERT INTO #{table_name} (#{key_str}) values (#{value_str})"
      end
      
      # returns an array of hashes. Each one has a {:event_type, :count, :most_recent} and is sorted by decending most_recent
      def groups
        Event.select("event_type, COUNT(event_type) as count, MAX(created_at) as most_recent").group("event_type").order("most_recent DESC").collect{|e|
          {
            :event_type => e["event_type"],
            :count => e["count"].to_i,
            :most_recent => Time.parse(e["most_recent"])
          }
        }
      end

      
      def get_details_for_event_type(type)
        Event.where(:event_type => type).select("COUNT(event_type) as count, MAX(created_at) as most_recent").group("event_type").collect{|e|
          {
            :event_type => type,
            :count => e["count"].to_i,
            :most_recent => Time.parse(e["most_recent"])
          }
        }.first
      end
      
    end
  end
end

app/controllers/i_wonder/ab_tests_controller.rb
module IWonder
  class AbTestsController < ApplicationController
    layout "i_wonder"
    
    if defined?(newrelic_ignore)
      newrelic_ignore
    end

    def index
      @ab_tests = AbTest.all
    end

    def show
      @ab_test = AbTest.find(params[:id])
    end

    def new
      @ab_test = AbTest.new(params[:ab_test])
    end

    def create
      @ab_test = AbTest.new(params[:ab_test])

      if @ab_test.save
        redirect_to @ab_test, :notice => "Successfully created ABTest"
      else
        render "new"
      end
    end

    def edit
      @ab_test = AbTest.find(params[:id])
      render "edit"
    end

    def update
      @ab_test = AbTest.find(params[:id])

      if @ab_test.update_attributes(params[:ab_test])
        redirect_to @ab_test, :notice => "Successfully updated ABTest"
      else
        render "edit"
      end
    end

    def destroy
      @ab_test = AbTest.find(params[:id])
      @ab_test.destroy
      redirect_to ab_tests_path, :notice => "ABTest has been destroyed"
    end
  end
end

app/controllers/i_wonder/application_controller.rb
# module IWonder
#   class ApplicationController < ActionController::Base
#   end
# end

app/controllers/i_wonder/dashboard_controller.rb
module IWonder
  class DashboardController < ApplicationController
    layout "i_wonder"
    
    if defined?(newrelic_ignore)
      newrelic_ignore
    end
    
    def landing
    end
    
  end
end

app/controllers/i_wonder/events_controller.rb
module IWonder
  class EventsController < ApplicationController
    layout "i_wonder"
    
    if defined?(newrelic_ignore)
      newrelic_ignore
    end
    
    def index
      @groups = Event.groups
    end
  
    def show
      @event_details = Event.get_details_for_event_type(params[:id])
    end
  
  end
end

app/controllers/i_wonder/metrics_controller.rb
module IWonder
  class MetricsController < ApplicationController
    layout "i_wonder"
    
    if defined?(newrelic_ignore)
      newrelic_ignore
    end

    def index
      @metrics = Metric.all
    end

    def show
      @metric = Metric.find(params[:id])
    end

    def new
      @metric = Metric.new(params[:metric])
    end

    def create
      @metric = Metric.new(params[:metric])

      if @metric.save
        redirect_to @metric, :notice => "Successfully created metric"
      else
        render "new"
      end
    end

    def edit
      @metric = Metric.find(params[:id])
      render "edit"
    end

    def update
      @metric = Metric.find(params[:id])

      if @metric.update_attributes(params[:metric])
        redirect_to @metric, :notice => "Successfully updated metric"
      else
        render "edit"
      end
    end

    def destroy
      @metric = Metric.find(params[:id])
      @metric.destroy
      redirect_to metrics_path, :notice => "Metric has been destroyed"
    end
  end
end

app/controllers/i_wonder/reports_controller.rb
module IWonder
  class ReportsController < ApplicationController
    layout "i_wonder"

    if defined?(newrelic_ignore)
      newrelic_ignore
    end

    def index
      @reports = Report.all
    end

    def show
      @report = Report.find(params[:id])

      @start_time = (params[:start_time] ? Time.zone.parse(params[:start_time]) : Time.zone.now - 1.month)
      @end_time = (params[:end_time] ? Time.zone.parse(params[:end_time]) : Time.zone.now)
      @interval_length = default_interval_length

      respond_to {|format|
        format.html { }
        format.js {
          if @report.line?
            render :partial => "line_report.js"
          else
            render :text => "?"
          end
        }
      }
    end

    def new
      @report = Report.new(params[:report])
    end

    def create
      @report = Report.new(params[:report])

      if @report.save
        redirect_to @report, :notice => "Successfully created report"
      else
        render "new"
      end
    end

    def edit
      @report = Report.find(params[:id])
      render "edit"
    end

    def update
      @report = Report.find(params[:id])

      if @report.update_attributes(params[:report])
        redirect_to @report, :notice => "Successfully updated report"
      else
        render "edit"
      end
    end

    def destroy
      @report = Report.find(params[:id])
      @report.destroy
      redirect_to reports_path, :notice => "Report has been destroyed"
    end

  protected

    def default_interval_length
      length = @end_time - @start_time

      if length > 2.months
        interval_length = 1.week
      elsif length > 1.week
        interval_length = 1.days
      else
        interval_length = 1.hours
      end

      # can't show a smaller frequency than the snampshots get taken in.
      longest_metric_frequency = @report.metrics.collect(&:frequency).max
      if longest_metric_frequency > interval_length
        interval_length = longest_metric_frequency
      end

      return interval_length
    end

  end
end

app/helpers/i_wonder/ab_tests_helper.rb
module IWonder
  module AbTestsHelper
  end
end

app/helpers/i_wonder/application_helper.rb
module IWonder
  module ApplicationHelper
  end
end

app/helpers/i_wonder/dashboard_helper.rb
module IWonder
  module DashboardHelper
  end
end

app/helpers/i_wonder/events_helper.rb
module IWonder
  module EventsHelper
  end
end

app/helpers/i_wonder/metrics_helper.rb
module IWonder
  module MetricsHelper
  end
end

app/helpers/i_wonder/reports_helper.rb
module IWonder
  module ReportsHelper
  end
end

app/views/i_wonder/ab_tests/_ab_test_goal_row.html.erb
<li class="ab_test_goal deletable_row">
	<%= f.hidden_field :id%>
	
	<%= f.select :goal_type, ["Event", "Page View"], {}, :onchange => "var row = $(this).closest('li'); row.find('.options').hide(); if($(this).val()=='Event'){ row.find('#event_options').show(); }else{ row.find('#page_view_options').show(); }" %>
	
	<div id="page_view_options" class='options' <% unless f.object.tracks_page_view? %> style="display:none" <% end %> >
		<%= f.text_field :page_view_controller, :placeholder => "controller", :size => 20 %>
		
		<%= f.text_field :page_view_action, :placeholder => "action (optional)", :size => 20 %>
	</div>
	
	<div id="event_options" class='options' <% unless f.object.tracks_event? %> style="display:none" <% end %> >
		<%= f.text_field :event_type, :placeholder => "event name" %>
	</div>
	
	<% if f.object.new_record? %>
		<%= link_to_function "", "$(this).closest('li').remove();", :class => "ui-icon ui-icon-circle-close delete" %>
	<% else%>
		<%= f.hidden_field :_destroy, :class => "hidden_destroy" %>
		<%= link_to_function "", "nested_delete(this);", :class => "ui-icon ui-icon-circle-close delete" %>
	<% end %>
	
</li>

app/views/i_wonder/ab_tests/_ab_test_goals.html.erb
<%= f.fields_for :ab_test_goals, IWonder::AbTestGoal.new, :child_index => "new_row_id" do |f2|%>
	<%= link_to_function "+ Add Goal", "$('#ab_test_goals').append(new_row_inserter(\"#{j render(:partial => "ab_test_goal_row", :locals => {:f => f2})}\"));", :id => "new_goal" %>
<% end %>

<h4>Goals</h4>

<ul id="ab_test_goals">
	<%= f.fields_for :ab_test_goals do |f2|%>
		<%= render :partial => "ab_test_goal_row", :locals => {:f => f2} %>
	<% end %>
</ul>

<br style="clear:both"/>

app/views/i_wonder/ab_tests/_ab_test_group_row.html.erb
<li class="ab_test_group deletable_row">
	<%= text_field_tag "ab_test[test_group_names][]", (defined?(test_group_name) ? test_group_name : ""), :placeholder => "Name..." %>
		
	<%= link_to_function "", "$(this).closest('li').remove();", :class => "ui-icon ui-icon-circle-close delete" %>
</li>

app/views/i_wonder/ab_tests/_ab_test_groups.html.erb
<%= link_to_function "+ Add Group", "$('#ab_test_groups').append(\"#{j render(:partial => "ab_test_group_row")}\");", :id => "new_goal" %>

<h4>Test Groups</h4>

<ul id="ab_test_groups">
	<% if f.object.test_group_names.empty? %> 
		<%= render :partial => "ab_test_group_row", :collection => ["", ""], :as => :test_group_name %>
	<% else %>
		<%= render :partial => "ab_test_group_row", :collection => f.object.test_group_names, :as => :test_group_name %>
	<% end %>
</ul>

<br style="clear:both"/>

app/views/i_wonder/ab_tests/_form.html.erb
<%= form_for @ab_test, :html => {:class => "main_form ab_test"} do |f| %>
	<% if @ab_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ab_test.errors.count, "error") %> prohibited this test from being saved:</h2>

      <ul>
      <% @ab_test.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<div class="field">
		<b>I wonder</b> <%= f.text_field :name, :placeholder => "test name...", :size => 50 %><b>?</b>
	</div>
	
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description, :rows => 3, :cols => 50%>
	</div>

	<div class="field">
		<%= f.label :test_applies_to %>
		<%= f.select :test_applies_to, [["Visitor", "session"], ["User", "user"], ["Account", "account"]] %><br/>
		<span class="description">If User or Account is selected but not available, the first option will be returned.</span>
	</div>
	
	
	<% if @ab_test.new_record? %>
		<div class="field">
			<%= f.label :sym, "Code reference symbol" %>
			<%= f.text_field :sym, :size => 15 %>
			<span class="description">letters numbers and underscores. NO spaces!</span>
		</div>
	<% end %>
	
	<hr/>
	
	<%= render :partial => "ab_test_groups", :locals => {:f => f} %>
	
	<hr/>

	<%= render :partial => "ab_test_goals", :locals => {:f => f} %>
	
	<hr/>
	
	<div class="field">
		<%= f.submit %>
	</div>
	
<% end %>

app/views/i_wonder/ab_tests/_show_not_started.html.erb
<p>
	This test hasn't started yet. Use the following code in a controller or view to begin:
</p>

<br/>
<p class="description">You can use the group name directly:</p>
<pre>&lt;%= which_test_group?("<%= @ab_test.sym %>") %&gt;</pre>

<p class="description">or run through different scenarios:</p>

<pre>
case which_test_group?("<%= @ab_test.sym %>")
<% for option_name in @ab_test.test_group_names -%>
when "<%= option_name%>"
	...
<% end -%>
else
	"Test Not Found"
end
</pre>

app/views/i_wonder/ab_tests/_show_report.html.erb
<table id="ab_test_summary" cellpadding=0 cellspacing=0>
	<thead>
		<tr>
			<td></td>
			<td>Assigned</td>
			
			<% for ab_test_goal in @ab_test.ab_test_goals do %>
				<td><%= ab_test_goal %></td>
			<% end %>
			
		</tr>
	</thead>
	
	<% for group_name in @ab_test.test_group_names do %>
		<tr>
			<td><%= group_name%></td>
			<td><%= @ab_test.test_group_memberships.where(:test_group_name => group_name).count %></td>
			
			<% for ab_test_goal in @ab_test.ab_test_goals do %>
				<td><%= @ab_test.get_results_for(group_name, ab_test_goal) %></td>
			<% end %>
			
			
		</tr>
	<% end %>
</table>

app/views/i_wonder/ab_tests/edit.html.erb
<h1>Edit AB Test</h1>

<%= render "form" %>

<p>
	<%= link_to "< cancel", @ab_test %>
</p>

app/views/i_wonder/ab_tests/index.html.erb
<h1>A/B Tests</h1>

<% if @ab_tests.empty? %>
	<p class="empty_list">You don't have any tests</p>
<% else %>
	<ul id="ab_test_list" class="primary_list">
		<% for ab_test in @ab_tests do %>
			<li>
				<%= link_to ab_test do %>
					<h3><span>I wonder</span> <%= ab_test.name %>?</h3>
					<p><%= ab_test.description %></p>
				<% end %>
			</li>
		<% end %>
	</ul>
<% end %>

<% if Rails.env.development? %>
	<p>
		<%= button_to "Create a new ABTest", url_for(:action => :new), :method => :get%>
	</p>
<% end %>

app/views/i_wonder/ab_tests/new.html.erb
<h1>New ABTest</h1>

<%= render "form" %>

<p>
	<%= link_to "< Back to index", ab_tests_path %>
</p>

app/views/i_wonder/ab_tests/show.html.erb
<div class="show">
	<% if Rails.env.development? %>
		<p>
			<%= link_to "Edit", edit_ab_test_path(@ab_test) %>
			|
			<%= link_to "Delete", @ab_test, :method => :delete, :confirm => "Are you sure?" %>
		</p>
	<% else %>
		<span class="description">No Modifying tests in production</span>
	<% end %>
	
	<h2>I wonder <%= @ab_test.name%>?</h2>
	<p class="description">
		<%= @ab_test.description.present? ? @ab_test.description : "no description..."%>
	</p>
	
	<% if @ab_test.started? %>
		<%= render "show_report" %>
	<% else %>
		<%= render "show_not_started" %>
	<% end %>
	
	
</div>